[tool.isort]
multi_line_output = 3
include_trailing_comma = true

[tool.ruff]
line-length = 100
lint.extend-select = ["ANN"]
lint.ignore = ["ANN401"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
docstring-code-format = true
docstring-code-line-length = 60